export const racas = [
    "Holandesa",
    "Jersey",
    "Angus",
    "Hereford",
    "Charolês",
    "Limousin",
    "Simmental",
    "Guzerá",
    "Pardo-Suíço",
    "Caracu",
    "Crioula",
    "Devon",
    "Brahman",
    "Brangus",
    "Santa Gertrudis",
    "Beefmaster",
    "Shorthorn",
    "Red Poll",
    "Ayrshire",
    "Milking Shorthorn",
    "Bazadaise",
    "Belgian Blue",
    "Belted Galloway",
    "Blonde d'Aquitaine",
    "Canadienne",
    "Chianina",
    "Dexter",
    "Droughtmaster",
    "Fleckvieh",
    "Friesian",
    "Gelbvieh",
    "Hérens",
    "Kerry",
    "Luing",
    "Marchigiana",
    "Montbéliarde",
    "Murray Grey",
    "Nelore",
    "Normande",
    "Parthenaise",
    "Piedmontese",
    "Pinzgauer",
    "Pustertaler Sprinzen",
    "Romagnola",
    "Salers",
    "South Devon",
    "Texas Longhorn",
    "Tuli",
    "Wagyu",
    "Welsh Black",
    "White Park",
    "Zebu",
    "Zwartbles"
  ]